---
title: "Cours-2-Data-Viz"
author: ''
date: '2019-09-16'
slug: cours-2-data-viz
tags: VIZ
categories: []
---
```{r}
data("iris")
donnee_Iris=read.table("C:/Users/10239/Desktop/iris.csv", header = T, sep=",", row.names = 1) #row.names permet de très la premiére colonnes comme nom de lignes.
View(donnee_Iris)
dim(donnee_Iris) #il y a 150 lignes
```
```{r}
donnee_Iris[,1:4]
head(donnee_Iris[,1:4])
```

```{r}
donnee_Iris[c(10,40,50), 1:4]

donnee_Iris[c(10,40,50), c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width")]
```

```{r}
donnee_Iris$Petal.Length
head(donnee_Iris$Petal.Length) #$permet d'acceder directement à une seule colonne a partir du jeu de données.
```

```{r}
dim(donnee_Iris[donnee_Iris$Species=="setosa",])
donnee_Iris$Species=="setosa" ##
```

```{r}
donnee_Iris[which(donnee_Iris$Species=="setosa"),]
which(donnee_Iris$Species=="setosa")
```

```{r}
dim(donnee_Iris[which(donnee_Iris$Species=="setosa"& donnee_Iris$Sepal.Width ==3.1 ),])

donnee_Iris[donnee_Iris$Species %in% c("setosa","versicolor"),]

donnee_Iris$Species %in% c("setosa", "versicolor")


```

```{r}
iris_subset1 = subset(donnee_Iris, Species == "setosa" & Sepal.Width ==3.1)
iris_subset1

iris_subset_setosa1 = subset(donnee_Iris, Species == "setosa" & Sepal.Width ==3.1,select=c("Sepal.Length","Petal.Length","Petal.Width"))
iris_subset_setosa1

```


```{r}
class(donnee_Iris$Species)
head(donnee_Iris$Species)

```

```{r}
rownames(donnee_Iris)= paste("iris", rownames(donnee_Iris), sep="")
donnee_Iris

summary(donnee_Iris)
```

```{r}
min(donnee_Iris[donnee_Iris$Species=="virginica",1])
mean(donnee_Iris[donnee_Iris$Species=="virginica",1])
max(donnee_Iris[donnee_Iris$Species=="virginica",1])

min(donnee_Iris[donnee_Iris$Species=="setosa",1])
mean(donnee_Iris[donnee_Iris$Species=="setosa",1])
max(donnee_Iris[donnee_Iris$Species=="setosa",1])

min(donnee_Iris[donnee_Iris$Species=="versicolor",1])
mean(donnee_Iris[donnee_Iris$Species=="versicolor",1])
max(donnee_Iris[donnee_Iris$Species=="versicolor",1])

data_iris_qualitative = donnee_Iris[,5]
```

```{r}
data_iris_qualitative =as.data.frame(donnee_Iris[,5])
data_iris_qualitative

rownames(data_iris_qualitative)= paste("iris", rownames(data_iris_qualitative), sep="")
colnames(data_iris_qualitative)=c("Spicies")
data_iris_qualitative


data_iris_quantitative = donnee_Iris[,c(1:4)]
data_iris_quantitative


#merge
data_iris_complet = merge(data_iris_quantitative, data_iris_qualitative, by="row.names")
data_iris_complet
rownames(data_iris_complet)=data_iris_complet[,1]
data_iris_complet=data_iris_complet[,-1]

cbind(data_iris_quantitative,data_iris_qualitative)
rbind(donnee_Iris,donnee_Iris)
dim(rbind(donnee_Iris,donnee_Iris))

3<4 
2<4 
4<2
4<3

3>4 
2>4 
4>2
4>3

4>=3 #4 est toujours supérieur ou ?gal à 3.
100>=2 # 100 est toujours quoi qu'il arrive supérieur ou ?gale à 2


3<=4
2<=100


1<=2 & 1<=3
1<=2 && 1<=3 # & ou && n'ont pas d'impact 

c(2,2)==c(2,2) & c(3,3)==c(3,3) #il va comparer les valeurs de chaque vecteur
c(2,2)==c(2,2) & c(3,3)==c(3,2) #il a comparà les valeurs de chaque vecteurs et il indique qu'il y a un probl?me puisque 3==2 c'est faux.

c(2,2)==c(2,2) && c(3,3)==c(3,3) 
c(2,2)==c(2,2) && c(3,3)==c(3,2) # dans cet exemple, l'op?rateur && va seulement comparer les premières valeurs de chaque vecteurs ce qui renvoi une r?ponse TRUE or c'est FALSE. Faire attention dans la manipulation de &&
```

```{r}

1<=2 | 1>=3
1<=2 || 1>=3 # l'une des deux propositions doit ?tre à TRUE.

c(2,2)==c(2,2) | c(3,3)==c(3,3)
c(2,2)==c(2,2) || c(3,3)==c(3,3)

c(2,2)==c(2,2) | c(3,3)==c(2,2)
c(2,2)==c(2,2) || c(3,3)==c(2,2)


# if(condition){
#   action 1
# } else {
#   action 2
# }
```

```{r}

if(3<=4 & 10==10){
  print("super action 1")
} else {
  print("pas super, donc action 2")
}

if(3<=4 & 10== 11){
  print("super action 1")
} else {
  print("pas super, donc action 2")
}


if(3 <=4 | 10== 11){
  print("super action 1")
} else {
  print("pas super, donc action 2")
}

if(3 >4 | 10== 11){
  print("super action 1")
} else {
  print("pas super, donc action 2")
}

 # for (condition){
 # action 
 # }

for (variable in c(1,2,3,4,5,6)) {
print(variable+1)  

}

for (variable in c(0:6)) {
print(variable+1)  

}

for (variable in c(1,2,3,4,5,6)) {
  print(paste("Chiffre num?ro : ", variable))  
  
}

for (variable in c(0:6)) {
  variable1= variable+1 
  if(variable1<=4){
    print("je suis dans la condition 1")
    print(variable1)
    
  } else {
    print("je suis dans la condition 2")
    print(variable1)
    
  }
}

valeur = 0
while (valeur <=4) {
  valeur = valeur +1
  print(valeur)
}
```

```{r}
valeur = 0
while (valeur <4) {
valeur = valeur +1
print(valeur)
}



nombre_versicolor= 0
nombre_setosa=0
nombre_virginica =0
for(espece in donnee_Iris$Species ){
  if(espece == "versicolor"){
    nombre_versicolor= nombre_versicolor+1
  }
  if(espece =="setosa")
    nombre_setosa=nombre_setosa+1
  
  if (espece =="virginica")
    nombre_virginica=nombre_virginica+1
}
print(paste("Nombre de versicolor ", nombre_versicolor))
print(paste("Nombre de setosa ", nombre_setosa))
print(paste("Nombre de virginica ", nombre_virginica))

nombre_versicolor= 0
nombre_setosa=0
nombre_virginica =0
for(espece in donnee_Iris$Species ){
  if(espece == "versicolor"){
    nombre_versicolor= nombre_versicolor+1
  } else
    if(espece =="setosa"){
      nombre_setosa=nombre_setosa+1
    }
  else{
    nombre_virginica=nombre_virginica+1
  }
}
print(paste("Nombre de versicolor ", nombre_versicolor))
print(paste("Nombre de setosa ", nombre_setosa))
print(paste("Nombre de virginica ", nombre_virginica))
```

```{r}
compteur_petal_4 =0
for (length in donnee_Iris$Petal.Length){
  if(length >=4){
    compteur_petal_4=compteur_petal_4+1
  }
}
compteur_petal_4

dim(donnee_Iris)

(dim(donnee_Iris))[1]


for (ligne in 1:dim(donnee_Iris)[1]){
  specimen = donnee_Iris[ligne,]
print(specimen)}


compteur_setosa_petal_5=0
for (ligne in 1:dim(donnee_Iris)[1]){
  specimen = donnee_Iris[ligne,]
if (specimen$Species =="setosa" & specimen$Sepal.Length >=5){
  compteur_setosa_petal_5=compteur_setosa_petal_5+1
}
}
print(compteur_setosa_petal_5)



for (colonne in 1:dim(donnee_Iris)[2]){
  specimen = donnee_Iris[,colonne]
  print(specimen)
  print("********************")
}



###Les fonctions 

  
  # nom_fonction =function(argument1, argument2,....etc){
  #   conditions et instructions
  #   bloc code
  #   return (resultat)
  # }


```
